Revert "Merge pull request #2836 from alphagov/dependabot/bundler/govspeak-10.6.2"
This reverts commit df209a7a7064dee35dd4703bee91f0c1f1bfc766, reversing
changes made to 08f4e0cc6391f6ac342183728e2eaccc682f7cd9.

Reverting the change as it appears to be breaking our `rake db:setup`
command with error:
```
** Invoke db:setup (first_time)
** Invoke db:create (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
TypeError: no implicit conversion of Array into String (TypeError)

          all = @files.select { |f| File.exist?(f) }
                                                ^
/govuk/publisher/config/environment.rb:5:in `<main>'
```