Revert "Merge pull request #2942 from alphagov/dependabot/bundler/govspeak-10.6.5"
This reverts commit 871d96a2425da0b2e5b16880f675c2d324461806, reversing
changes made to 462c8138fc671e400a8e5e3fa471e74e916ee9a7.

The publisher app fails to start with this updated govspeak gem:
```
** Invoke db:setup (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
TypeError: no implicit conversion of Array into String (TypeError)

          all = @files.select { |f| File.exist?(f) }
```